services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    env_file:
      - .env
    container_name: pgdb
    networks:
      - app_network

networks:
  app_network:
    driver: bridge